name: Environment variable

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Set system env variable
        run: |
          echo "SMILE=😊" >> $GITHUB_ENV 
      - name: "Say Hello Ishtiyaq it's Thursday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! $SMILE"
        env:
          First_Name: Ishtiyaq
